### PR TITLE
8269657: Test java/nio/channels/DatagramChannel/Loopback.java failed: Unexpected message

### PR DESCRIPTION
**Pull request by Shivangi-aa**
Straight Backport

https://mach5.us.oracle.com/mdash/jobs/sshivang-adhoc-20240714-0825-13799277

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8269657](https://bugs.openjdk.org/browse/JDK-8269657) needs maintainer approval

### Issue
 * [JDK-8269657](https://bugs.openjdk.org/browse/JDK-8269657): Test java/nio/channels/DatagramChannel/Loopback.java failed: Unexpected message (**Bug** - P3 - Requested)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/20/head:pull/20` \
`$ git checkout pull/20`

Update a local copy of the PR: \
`$ git checkout pull/20` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/20/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20`

View PR using the GUI difftool: \
`$ git pr show -t 20`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/20.diff">https://git.openjdk.org/jdk23u/pull/20.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/20#issuecomment-2227276449)

### CODE REVIEW

**Comment by Shivangi-aa** [comment]
/approval JDK-8269657 request Backporting bug to 23 as failing in lower releases CI

**Comment by sendaoYan** [comment]
Does this duplicated to https://github.com/openjdk/jdk/pull/19936

**Comment by Shivangi-aa** [comment]
Yeah right it is duplicate to https://github.com/openjdk/jdk/pull/19936

**Comment by Shivangi-aa** [comment]
Looks Like duplicate https://github.com/openjdk/jdk/pull/19936

**Comment by kevinrushforth** [comment]
@Shivangi-aa In that case, please close this jdk23u PR. A fix for the JDK 23 release family is backported to either `jdk:jdk23` or `jdk23u`, _never_ both.

**Pull request closed without merging**
