### PR TITLE
8337876: [IR Framework] Add support for IR tests with @Stable

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to improve IR Framework for upcoming tests.

Additional testing:
 - [x] MacOS AArch64 server fastdebug, `testlibrary_tests/ir_framework` passes

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8338112](https://bugs.openjdk.org/browse/JDK-8338112) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8337876](https://bugs.openjdk.org/browse/JDK-8337876) needs maintainer approval

### Issues
 * [JDK-8337876](https://bugs.openjdk.org/browse/JDK-8337876): [IR Framework] Add support for IR tests with @Stable (**Enhancement** - P4 - Approved)
 * [JDK-8338112](https://bugs.openjdk.org/browse/JDK-8338112): Test testlibrary_tests/ir_framework/tests/TestPrivilegedMode.java fails with release build (**Bug** - P4 - Approved)

### Reviewers
 * [Evgeny Astigeevich](https://openjdk.org/census#eastigeevich) (@eastig - Author)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/62/head:pull/62` \
`$ git checkout pull/62`

Update a local copy of the PR: \
`$ git checkout pull/62` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/62/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 62`

View PR using the GUI difftool: \
`$ git pr show -t 62`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/62.diff">https://git.openjdk.org/jdk23u/pull/62.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/62#issuecomment-2283619239)

### CODE REVIEW

**Comment by shipilev** [comment]
/approval request Clean backport to improve IR Framework for upcoming tests. Applies cleanly. IR Framework tests pass.

**Comment by shipilev** [comment]
/approval 8338112 request Follow-up for 8337876 to fix the test in release builds. Applies cleanly. Release JDK passes the test. Risk is low, test-only change.

**Comment by shipilev** [comment]
Both backports are actually clean. The PR is not marked clean because we have two bugs references in it.

/clean

**Comment by shipilev** [comment]
> @shipilev The `/clean` pull request command is not enabled for this repository

:(  Need some reviews then, please.

**Review by eastig — APPROVED** [review]
Confirming it's a clean backport.

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
