### PR TITLE
8339416: [s390x] Provide implementation for resolve_global_jobject

### PR DESCRIPTION
**Pull request by offamitkumar**
Hi all,

This pull request contains a backport of commit [ac58b610](https://github.com/openjdk/jdk/commit/ac58b6102a26ac2ca7f6df5f176d5b5ca1d00d45) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Amit Kumar on 19 Sep 2024 and was reviewed by Martin Doerr and Lutz Schmidt.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8339416](https://bugs.openjdk.org/browse/JDK-8339416) needs maintainer approval

### Issue
 * [JDK-8339416](https://bugs.openjdk.org/browse/JDK-8339416): [s390x] Provide implementation for resolve_global_jobject (**Enhancement** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/110/head:pull/110` \
`$ git checkout pull/110`

Update a local copy of the PR: \
`$ git checkout pull/110` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/110/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 110`

View PR using the GUI difftool: \
`$ git pr show -t 110`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/110.diff">https://git.openjdk.org/jdk23u/pull/110.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/110#issuecomment-2362789178)

### CODE REVIEW

**Comment by offamitkumar** [comment]
/approval request backporting it to be in sync with other archs, low risk & s390x specific change. Didn't see any regression during testing.

**Comment by offamitkumar** [comment]
@RealLucy 👀

**Comment by shipilev** [comment]
@offamitkumar 👀 

/sponsor

**Comment by offamitkumar** [comment]
Thanks @shipilev :-)

**Pull request closed without merging**
