### PR TITLE
8337664: Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs

### PR DESCRIPTION
**Pull request by pkumaraswamy**
This is a clean backport.
Internal tests are green and related jck tests are green as well

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8339194](https://bugs.openjdk.org/browse/JDK-8339194) to be approved
- [x] [JDK-8337664](https://bugs.openjdk.org/browse/JDK-8337664) needs maintainer approval

### Issues
 * [JDK-8337664](https://bugs.openjdk.org/browse/JDK-8337664): Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs (**Enhancement** - P3 - Approved)
 * [JDK-8339194](https://bugs.openjdk.org/browse/JDK-8339194): Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/91/head:pull/91` \
`$ git checkout pull/91`

Update a local copy of the PR: \
`$ git checkout pull/91` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/91/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 91`

View PR using the GUI difftool: \
`$ git pr show -t 91`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/91.diff">https://git.openjdk.org/jdk23u/pull/91.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/91#issuecomment-2327997965)

### CODE REVIEW

**Comment by coffeys** [comment]
> @pkumaraswamy , @coffeys For some reason the backport is not annotated to the bug. Did you eventually make a closed backport somehow? Could you please open it up?

the issue should now be visible.  As per JDK crypto roadmap - the aim is for October release:
https://www.java.com/en/jre-jdk-cryptoroadmap.html

**Comment by GoeLin** [comment]
Thanks for the info and opening the issues!

**Pull request closed without merging**
