### PR TITLE
8337795: Type annotation attached to incorrect type during class reading

### PR DESCRIPTION
**Pull request by cushon**
This change fixes a bug in javac's handling of type annotations in bytecode, which was logic first added in JDK 22 as part of the fix for JDK-8225377.

---------
### Progress
- [x] [JDK-8337795](https://bugs.openjdk.org/browse/JDK-8337795) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337795](https://bugs.openjdk.org/browse/JDK-8337795): Type annotation attached to incorrect type during class reading (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/67/head:pull/67` \
`$ git checkout pull/67`

Update a local copy of the PR: \
`$ git checkout pull/67` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/67/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 67`

View PR using the GUI difftool: \
`$ git pr show -t 67`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/67.diff">https://git.openjdk.org/jdk23u/pull/67.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/67#issuecomment-2286758681)

### CODE REVIEW

**Comment by cushon** [comment]
/approval request This change fixes a bug in javac's handling of type annotations in bytecode, which was logic first added in JDK 22 as part of the fix for JDK-8225377. The patch applies cleanly, and langtools tier1 passes.

**Comment by cushon** [comment]
> Feel free to ask for assistance if you need help with progressing this pull request towards integration!

The backport has maintainer approval, is there anything else I should be doing to help progress this towards integration?

**Comment by phohensee** [comment]
Add a "/integrate" comment and I'll sponsor.

**Pull request closed without merging**
