### PR TITLE
8334057: JLinkReproducibleTest.java support receive test.tool.vm.opts

### PR DESCRIPTION
**Pull request by abhn-git**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8334057](https://bugs.openjdk.org/browse/JDK-8334057) needs maintainer approval

### Issue
 * [JDK-8334057](https://bugs.openjdk.org/browse/JDK-8334057): JLinkReproducibleTest.java support receive test.tool.vm.opts (**Sub-task** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/40/head:pull/40` \
`$ git checkout pull/40`

Update a local copy of the PR: \
`$ git checkout pull/40` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/40/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 40`

View PR using the GUI difftool: \
`$ git pr show -t 40`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/40.diff">https://git.openjdk.org/jdk23u/pull/40.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/40#issuecomment-2344800834)

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please send me an email at dalibor.topic@oracle.com so that I can take care of verifying your account in Skara.

**Comment by abhn-git** [comment]
Can some one please sponsor this changeset

**Comment by gdams** [comment]
> Looks to me #25 was here first, so we would probably integrate that?
> 
> Going forward, please enable GHA tests for new PRs, see "Pre-submit test status" in "Checks" above.

just re-read this. yeah sorry it's already been integrated in #25

**Pull request closed without merging**
