### PR TITLE
8341966: Broken annotated module may lead to an exception in javac

### PR DESCRIPTION
**Pull request by lahodaj**
Hi all,

    This pull request contains a backport of commit [7ff4ea8d](https://github.com/openjdk/jdk/commit/7ff4ea8d01c681b90ad59be04007557d84c8db94) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

    The commit being backported was authored by Jan Lahoda on 17 Oct 2024 and was reviewed by Adam Sotona.

    Thanks!

The original description:

Consider a `module-info.class`, that both:
 - is wrong, so it will produce a bad-classfile error, for example due to an illegal `requires transitive java.base;`
 - and the module is annotated

If the javac proceeds to resolve the annotations (which is not the default, but can be pushed to do it), it will crash with an `AssertionError` while trying to un-proxy the annotations. This is because there's an assert that `requestingOwner.owner.kind == MDL`, but since the module is erroneous, the kind is `ERR`, and the assert fails.

The proposal is to loosen the assert a bit, and require `requestingOwner.owner instanceof ModuleSymbol`. That should still be sufficiently strong, while permitting broken modules to be handled.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8341966](https://bugs.openjdk.org/browse/JDK-8341966) needs maintainer approval

### Issue
 * [JDK-8341966](https://bugs.openjdk.org/browse/JDK-8341966): Broken annotated module may lead to an exception in javac (**Task** - P4 - Approved)

### Reviewers
 * [Adam Sotona](https://openjdk.org/census#asotona) (@asotona - no project role)
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/192/head:pull/192` \
`$ git checkout pull/192`

Update a local copy of the PR: \
`$ git checkout pull/192` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/192/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 192`

View PR using the GUI difftool: \
`$ git pr show -t 192`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/192.diff">https://git.openjdk.org/jdk23u/pull/192.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/192#issuecomment-2419041024)

### CODE REVIEW

**Comment by lahodaj** [comment]
/approval request This problem crashes javac with an exception when working with erroneous module-info.class. javac should report an error (and it does) but should not crash. The fix is just to down-tune an assert, so it should be very safe. Thanks!

**Review by asotona — APPROVED** [review]
Looks good to me.

**Review by vicente-romero-oracle — APPROVED** [review]
lgtm

**Pull request closed without merging**
