### PR TITLE
8337753: Target class of upcall stub may be unloaded

### PR DESCRIPTION
**Pull request by JornVernee**
Backport of: https://github.com/openjdk/jdk/pull/20479

There were some trivial conflicts in `stubGenerator_aarch64.cpp` and `stubGenerator_riscv.cpp`. Some code still there in jdk23, already removed in later versions.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8337753](https://bugs.openjdk.org/browse/JDK-8337753) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337753](https://bugs.openjdk.org/browse/JDK-8337753): Target class of upcall stub may be unloaded (**Bug** - P3 - Approved)

### Reviewers
 * [Vladimir Ivanov](https://openjdk.org/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/163/head:pull/163` \
`$ git checkout pull/163`

Update a local copy of the PR: \
`$ git checkout pull/163` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/163/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 163`

View PR using the GUI difftool: \
`$ git pr show -t 163`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/163.diff">https://git.openjdk.org/jdk23u/pull/163.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/163#issuecomment-2411123299)

### CODE REVIEW

**Comment by MikOfClassX** [comment]
I've got a lot of these:

# JRE version: OpenJDK Runtime Environment Temurin-23.0.1+11 (23.0.1+11) (build 23.0.1+11)
#  Internal Error (sharedRuntime.cpp:1423), pid=36540, tid=44512
#  guarantee(callee != nullptr && callee->is_method()) failed: bad handshake

So, I'm waiting for this fix in java23... (_02 ?)
Thanks!

**Comment by JornVernee** [comment]
After discussion, decided to not fix this in jdk23u. The fix is not exactly low-risk, and the scenario in which it occurs is fairly rare: only when many threads are racing to create FFM upcall stubs targeting the same Java method (really the same LambdaForm) at the same time, and we've only been able to reproduce on Linux/aarch64 so far. Given the current release timeline for jdk23u, if this fix does end up causing a regression, we might not have enough time to address it for jdk23u GA.

**Comment by JornVernee** [comment]
> we're experiencing frequent crashes on JDK (windows+zgc)

Thanks, that is useful information. I'm assuming you're using an x64 machine to run this?

A reproducer would certainly help, but as I also found during testing that the issue triggering is very much dependent on other noise generated by the application.

**Comment by pabloko** [comment]
Yeah, i've spent a good time triying to isolate and reproduce the issue to do a bugreport without much success, but definitely we're behind of this for some months now as we early and widely adopted FFM back on jdk19. 

In our case, we have calls originating from a remote thread pool from 3rd party library, wich is a fairly common use case. 

We had initially checked that the native code is not producing exceptions and the same for the java code, in fact, we wrap our MethodHandle lookups like this to avoid possible java exceptions.
```java
return MethodHandles.catchException(MethodHandles.lookup().findVirtual(obj.getClass(), methodName, functionDescriptor.toMethodType()), Throwable.class, MethodHandles.empty(MethodType.methodType(functionDescriptor.toMethodType().returnType(), Throwable.class))).bindTo(obj)
```
Later we observed that different combinations of threading while allocating upcalls with `Arena.ofShared()` would crash the jvm on `System.gc()` but `Arena.ofAuto()` would not, but still crash randomly at some point... We also tried a variety of testing flags like SafepointALot/HandshakeALot and similar ones without any noticeable effects, and at that point we stated considering a jdk implementation bug and following the rabbit hole until we seen the [commit log](https://github.com/openjdk/jdk/pull/20479) of the original PR, and it all made sense.

In any case, we're available to conduct any further testing needed to resolve the issue since we're still able to trigger itWe're available to conduct any further testing needed to resolve the issue since we're still able to trigger it. Additionally, we confirm that this PR seems to fix it effectively in our ad-hoc builds.

**Review by iwanowww — APPROVED** [review]
Looks good.

**Pull request closed without merging**
