### PR TITLE
8342489: compiler/c2/irTests/TestVectorizationMismatchedAccess.java fails on big-endian platforms

### PR DESCRIPTION
**Pull request by offamitkumar**
Hi all,

This pull request contains a backport of commit [b6f745df](https://github.com/openjdk/jdk/commit/b6f745df5795341dab1fc049a188a9e70d563a1a) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Amit Kumar on 30 Oct 2024 and was reviewed by Emanuel Peter and Matthias Baesken.

Thanks!

---------
### Progress
- [x] [JDK-8342489](https://bugs.openjdk.org/browse/JDK-8342489) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8342489](https://bugs.openjdk.org/browse/JDK-8342489): compiler/c2/irTests/TestVectorizationMismatchedAccess.java fails on big-endian platforms (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk23u.git pull/211/head:pull/211` \
`$ git checkout pull/211`

Update a local copy of the PR: \
`$ git checkout pull/211` \
`$ git pull https://git.openjdk.org/jdk23u.git pull/211/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 211`

View PR using the GUI difftool: \
`$ git pr show -t 211`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk23u/pull/211.diff">https://git.openjdk.org/jdk23u/pull/211.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk23u/pull/211#issuecomment-2445763266)
</details>

### CODE REVIEW

**Comment by offamitkumar** [comment]
/approval request test fails on big endian platforms(s390x & ppc-aix). this fix adjust test-case according to big endian platforms as well and behaviour for little endian platform is unchanged. It is of Low risk and tested on both s390x & ppc-aix.

**Comment by offamitkumar** [comment]
@MBaesken can you sponsor this change, please.

**Comment by MBaesken** [comment]
Sure !

/sponsor

**Pull request closed without merging**
